#!/usr/bin/env python3
"""
View intermediate outputs from PIXIU evaluation.

This script reads the *_write_out_info.json files generated by PIXIU
and displays model inputs, outputs, predictions, and gold labels for each sample.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Any, List


def load_write_out_info(file_path: Path) -> Dict[str, Any]:
    """Load write_out_info.json file."""
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def format_sample_output(sample: Dict[str, Any], doc_id: int) -> str:
    """Format a single sample's output for display."""
    lines = []
    lines.append("=" * 80)
    lines.append(f"Sample ID: {doc_id}")
    lines.append("=" * 80)
    
    # Model input (prompt)
    if "prompt_0" in sample:
        lines.append("\n[Model Input / Prompt]:")
        lines.append("-" * 80)
        lines.append(sample["prompt_0"])
    
    # Model output (raw)
    if "logit_0" in sample:
        lines.append("\n[Model Output (Raw)]:")
        lines.append("-" * 80)
        lines.append(sample["logit_0"])
    
    # Prediction (processed)
    if "pred" in sample:
        lines.append("\n[Prediction (Processed)]:")
        lines.append("-" * 80)
        lines.append(sample["pred"])
    
    # Gold label
    if "truth" in sample:
        lines.append("\n[Gold Label]:")
        lines.append("-" * 80)
        lines.append(str(sample["truth"]))
    elif "gold" in sample:
        lines.append("\n[Gold Label]:")
        lines.append("-" * 80)
        lines.append(str(sample["gold"]))
    
    # Metrics
    metric_keys = [k for k in sample.keys() if k not in ["doc_id", "prompt_0", "logit_0", "pred", "truth", "gold"]]
    if metric_keys:
        lines.append("\n[Metrics]:")
        lines.append("-" * 80)
        for key in sorted(metric_keys):
            if key.startswith("logit_") or key.startswith("prompt_"):
                continue
            lines.append(f"  {key}: {sample[key]}")
    
    lines.append("")
    return "\n".join(lines)


def view_samples(
    file_path: Path,
    sample_ids: List[int] = None,
    max_samples: int = None,
    show_all: bool = False
):
    """View intermediate outputs for specified samples."""
    data = load_write_out_info(file_path)
    
    # Get all sample IDs
    all_ids = sorted([int(k) for k in data.keys() if k.isdigit()])
    
    if show_all:
        sample_ids = all_ids
    elif sample_ids is None:
        sample_ids = all_ids[:max_samples] if max_samples else all_ids
    
    print(f"\nFound {len(all_ids)} samples in {file_path.name}")
    print(f"Displaying {len(sample_ids)} samples\n")
    
    for doc_id in sample_ids:
        doc_id_str = str(doc_id)
        if doc_id_str not in data:
            print(f"Warning: Sample {doc_id} not found")
            continue
        
        sample = data[doc_id_str]
        print(format_sample_output(sample, doc_id))


def view_summary(file_path: Path):
    """View summary statistics."""
    data = load_write_out_info(file_path)
    
    all_ids = sorted([int(k) for k in data.keys() if k.isdigit()])
    
    print(f"\nSummary for {file_path.name}")
    print("=" * 80)
    print(f"Total samples: {len(all_ids)}")
    
    # Count correct/incorrect if acc is available
    correct = 0
    incorrect = 0
    missing = 0
    
    for doc_id_str in all_ids:
        sample = data[str(doc_id_str)]
        if "acc" in sample:
            acc = float(sample["acc"])
            if acc > 0.5:
                correct += 1
            else:
                incorrect += 1
        if "missing" in sample:
            if int(sample["missing"]) > 0:
                missing += 1
    
    if correct + incorrect > 0:
        print(f"Correct: {correct}")
        print(f"Incorrect: {incorrect}")
        print(f"Accuracy: {correct / (correct + incorrect) * 100:.2f}%")
    
    if missing > 0:
        print(f"Missing predictions: {missing}")
    
    print()


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description="View intermediate outputs from PIXIU evaluation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # View all samples
  python view_intermediate_outputs.py en-fpb_write_out_info.json --all

  # View first 5 samples
  python view_intermediate_outputs.py en-fpb_write_out_info.json --max 5

  # View specific samples
  python view_intermediate_outputs.py en-fpb_write_out_info.json --samples 0 1 2

  # View summary only
  python view_intermediate_outputs.py en-fpb_write_out_info.json --summary
        """
    )
    
    parser.add_argument(
        "file",
        type=Path,
        help="Path to *_write_out_info.json file"
    )
    parser.add_argument(
        "--samples", "-s",
        type=int,
        nargs="+",
        help="Specific sample IDs to view"
    )
    parser.add_argument(
        "--max", "-m",
        type=int,
        help="Maximum number of samples to view"
    )
    parser.add_argument(
        "--all", "-a",
        action="store_true",
        help="View all samples"
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Show summary statistics only"
    )
    
    args = parser.parse_args()
    
    if args.summary:
        view_summary(args.file)
    else:
        view_samples(
            args.file,
            sample_ids=args.samples,
            max_samples=args.max,
            show_all=args.all
        )


if __name__ == "__main__":
    main()

